env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['htmlacademy/es6', 'plugin:react/recommended', 'plugin:@typescript-eslint/recommended']

parser: '@typescript-eslint/parser'

plugins: ['react']

settings:
  react:
    version: '16'

rules:
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-use-before-define': 'off'
  'eslint/quotes': 'off'
  'react/prop-types': 'off'
